import combinatorial_properties_polytopes_polyhedra_number_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace combinatorial_properties_polytopes_polyhedra_number_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end combinatorial_properties_polytopes_polyhedra_number_lemma_canonical_lane_mathlib
end HautevilleHouse
